//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int chat_num { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
        public string last_message { get; set; }
        public string user_id1 { get; set; }
        public string user_id2 { get; set; }
        public string dateStr { get; set; }
        public string timeStr { get; set; }
        public string last_message_sent_by { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
