//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class horseClubDbContext : DbContext
    {
        public horseClubDbContext()
            : base("name=horseClubDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<horse> horses { get; set; }
        public virtual DbSet<parent> parents { get; set; }
        public virtual DbSet<rider> riders { get; set; }
        public virtual DbSet<trial_lesson> trial_lesson { get; set; }
        public virtual DbSet<visitor> visitors { get; set; }
        public virtual DbSet<worker> workers { get; set; }
        public virtual DbSet<regular_lesson> regular_lesson { get; set; }
        public virtual DbSet<chat> chats { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<lesson> lessons { get; set; }
        public virtual DbSet<instructor_feedback> instructor_feedback { get; set; }
        public virtual DbSet<rider_feedback> rider_feedback { get; set; }
        public virtual DbSet<match_criteria> match_criteria { get; set; }
    }
}
