//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class horse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public horse()
        {
            this.riders = new HashSet<rider>();
            this.trial_lesson = new HashSet<trial_lesson>();
            this.lessons = new HashSet<lesson>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public string size { get; set; }
        public string temper { get; set; }
        public Nullable<int> required_rank { get; set; }
        public Nullable<int> max_weight { get; set; }
        public Nullable<int> min_weight { get; set; }
        public Nullable<double> max_height { get; set; }
        public Nullable<double> min_height { get; set; }
        public Nullable<bool> therapeutic_riding { get; set; }
        public Nullable<bool> can_jump { get; set; }
        public Nullable<bool> is_qualified { get; set; }
        public Nullable<bool> is_active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rider> riders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trial_lesson> trial_lesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lesson> lessons { get; set; }
    }
}
