//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class instructor_feedback
    {
        public int feedback_id { get; set; }
        public Nullable<int> lesson_id { get; set; }
        public Nullable<int> q1 { get; set; }
        public Nullable<int> q2 { get; set; }
        public Nullable<int> q3 { get; set; }
        public Nullable<int> q4 { get; set; }
        public Nullable<double> score { get; set; }
    
        public virtual lesson lesson { get; set; }
    }
}
