//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lesson()
        {
            this.notifications = new HashSet<notification>();
            this.instructor_feedback = new HashSet<instructor_feedback>();
            this.rider_feedback = new HashSet<rider_feedback>();
        }
    
        public int lesson_id { get; set; }
        public System.DateTime date { get; set; }
        public System.TimeSpan start_time { get; set; }
        public string rider_id { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public Nullable<int> horse_id { get; set; }
        public string instructor_id { get; set; }
        public string field { get; set; }
        public string lesson_type { get; set; }
        public Nullable<int> price { get; set; }
        public string funding_source { get; set; }
        public string charge_type { get; set; }
        public string was_present { get; set; }
        public string comments { get; set; }
        public Nullable<double> match_rank { get; set; }
    
        public virtual horse horse { get; set; }
        public virtual worker worker { get; set; }
        public virtual rider rider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notification> notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instructor_feedback> instructor_feedback { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rider_feedback> rider_feedback { get; set; }
    }
}
