//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class match_criteria
    {
        public int criterion_id { get; set; }
        public string criterion_name { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<double> criterion_weight { get; set; }
        public string criterion_description { get; set; }
        public Nullable<double> min_weight { get; set; }
        public Nullable<double> max_weight { get; set; }
    }
}
