//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class trial_lesson
    {
        public System.DateTime date { get; set; }
        public string visitor_id { get; set; }
        public Nullable<int> horse_id { get; set; }
        public string instructor_id { get; set; }
        public string field { get; set; }
        public Nullable<int> price { get; set; }
        public string funding_source { get; set; }
        public string charge_type { get; set; }
        public string was_present { get; set; }
        public string comments { get; set; }
        public int lesson_id { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
        public string lesson_type { get; set; }
    
        public virtual horse horse { get; set; }
        public virtual worker worker { get; set; }
        public virtual visitor visitor { get; set; }
    }
}
